### ISSUE TITLE
Support new packages file in dart 1.12

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/coverage#100]
The format coverage task takes a `--package-root` option to discover packages. This fails in projects using dart 1.12 with the `--no-package-symlinks` flag.

**Comment by cbracken** [comment]
Will try to get a patch landed for this today!

**Comment by abarth** [comment]
I'm hitting this issue too in trying to integrate `package:coverage` with Flutter.

**Comment by cbracken** [comment]
Fixed by 402b821104e58c0b5e5c583af2e64fb9d21a194c.

**Comment by cbracken** [comment]
This is released in version (0.7.8)[https://pub.dartlang.org/packages/coverage].
