### ISSUE TITLE
Needs to be updated to support Dart 1.16 service protocol

### ISSUE THREAD

**Issue by pulyaevskiy** [dart-lang/coverage#107]
I haven't upgraded to 1.16 yet, but Travis builds suddenly started to fail with following error:

```
$ pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates
JSON-RPC error -32601 (method not found): Method not found
package:json_rpc_2/src/client.dart 99            Client.sendRequest
package:json_rpc_2/src/peer.dart 94              Peer.sendRequest
package:coverage/src/vm_service_client.dart 198  VMServiceClient.getCoverage.<async>
===== asynchronous gap ===========================
dart:async                                       Future.Future.microtask
package:coverage/src/vm_service_client.dart      VMServiceClient.getCoverage
package:coverage/src/collect.dart 41             _getAllCoverage.<async>
dart:async                                       _SyncCompleter.complete
package:vm_service_client/src/isolate.dart 232   VMIsolateRef.load.<async>
dart:async                                       _SyncCompleter.complete
package:vm_service_client/src/scope.dart 51      Scope.sendRequest.<async>
dart:async                                       _SyncCompleter.complete
package:json_rpc_2/src/client.dart 178           Client._handleSingleResponse
package:json_rpc_2/src/client.dart 168           Client._handleResponse
dart:async                                       _StreamController.add
package:json_rpc_2/src/peer.dart 117             Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                       _asyncThenWrapperHelper
package:coverage/src/collect.dart                _getAllCoverage
package:coverage/src/collect.dart 26             collect.<async>
dart:async                                       _SyncCompleter.complete
package:coverage/src/util.dart 39                retry.<async>.<fn>.<async>
dart:async                                       _SyncCompleter.complete
package:coverage/src/vm_service_client.dart 90   VMServiceClient.connect.<async>
===== asynchronous gap ===========================
dart:async                                       _asyncThenWrapperHelper
package:coverage/src/collect.dart                collect
http://localhost:52493/collect_coverage.dart 21  main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                              Chain.capture
http://localhost:52493/collect_coverage.dart 20  main.<async>
```

Example of a full build log: https://travis-ci.org/corsac-dart/bootstrap/builds/125995686

coverage package is enabled via `pub global activate` and the log shows that some packages are not latest version, e.g.:

```
$ pub global activate coverage
Resolving dependencies... (1.5s) 
+ args 0.13.4
+ async 1.10.0
+ collection 1.5.1
+ coverage 0.7.3
+ json_rpc_2 1.2.0 (2.0.1 available)
+ logging 0.11.3
+ path 1.3.9
+ pub_semver 1.2.4
+ source_span 1.2.2
+ stack_trace 1.6.5
+ vm_service_client 0.1.3 (0.2.0 available)
```

I'm wondering if that's the reason, and if we need an updated version of this package published with latest dependencies?

**Comment by travissanderson-wf** [comment]
We are seeing the same thing with our build systems

**Comment by kevmoo** [comment]
Related - https://github.com/dart-lang/vm_service_client/issues/6

**Comment by kevmoo** [comment]
FYI: I'm working hard to get this resolved

I'm almost ready to last the fix (https://github.com/dart-lang/vm_service_client/issues/6) for the blocking issue (https://github.com/dart-lang/vm_service_client/issues/6)

I've already started on migrating the coverage package to this.

**Comment by travissanderson-wf** [comment]
Thanks for the update, I saw movement in the vm_service_client and figured as much but appreciate the post.

**Comment by kevmoo** [comment]
We've got the vm_service_client updated.

I'm doing work here - https://github.com/dart-lang/coverage/tree/migration

I'd really like to parse down what coverage does.

Is anyone consuming it for something other than coveralls.io?

**Comment by pulyaevskiy** [comment]
I have couple builds for codecov. Would be happy to help

**Comment by evanweible-wf** [comment]
@kevmoo all of our packages at Workiva use codecov, although we collect coverage via [dart_dev](https://github.com/Workiva/dart_dev). It essentially just combines the two steps from this package (collect and format) into a single task, handles merging coverage if the package has multiple suites, and a few other things like auto-generating an HTML file and generating the HTML report. It's always been brittle though, so I'm not opposed to change. I'm also happy to help!

**Comment by kevmoo** [comment]
@evanweible-wf do you have sample code? What format do you use for upload, etc?

**Comment by evanweible-wf** [comment]
Sure. The reporting to codecov part is easy, they supply a bash script that takes a correctly formatted coverage file (lcov, gcov, json, etc):

```bash
pub run dart_dev coverage --no-html
bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
```
> https://github.com/Workiva/w_transport/blob/master/.travis.yml#L13-L14

The coverage task in dart_dev handles running the `coverage` executables across a set of test files and producing a single `.lcov` file: https://github.com/Workiva/dart_dev/blob/master/lib/src/tasks/coverage/api.dart

**Comment by donny-dont** [comment]
@kevmoo I use https://aircover.co/ for my stuff. It takes in lcov and then pushes it to the server. The pushing is done in a plugin so the lcov just needs to be hanging out somewhere on the disk.

**Comment by kevmoo** [comment]
With this pull request - https://github.com/dart-lang/coverage/pull/108 - we have the ability to connect to a running dart app (with the vm service enabled) and collect LCOV coverage info.

I'll work with @cbracken to review the code. If you're itchy to get coverage working on your app, you could try out the code on your own box.

I've cleaned up the API and the binaries A LOT. Let me know if you miss anything I've removed.

**Comment by cbracken** [comment]
For anyone who needs SDK 1.16.0 support straight away while #108 is in review, I've pushed [a patched branch](https://github.com/cbracken/coverage/tree/sdk_1_16) of what we use inside Google for code coverage.

**Comment by cbracken** [comment]
Closed by 521c4e5df41a961cbd4ffdd8b45015b2c2daefdd. Released in [version 0.7.4](https://pub.dartlang.org/packages/coverage).

**Comment by alexander-doroshko** [comment]
Verified that coverage works again in WebStorm 2016.2, thanks a lot!

**Comment by cbracken** [comment]
Thanks for verifying!
