### ISSUE TITLE
Minimise transitive dependencies to a reasonable set

### ISSUE THREAD

**Issue by cbracken** [dart-lang/coverage#109]
@kevmoo @nex3 

f3dfba44dd038742857c1b9c01adbaf2080f6838 killed off `devtools.dart` (hooray!) and moved us over to `package:vm_service_client`. Unfortunately, it appears this change massively increased the set of dependencies; our deps went from `args`, `logging`, and `path`, to 36 deps including `analyzer`, `csslib` , `html`, `shelf`, and others.

The bad news is that this makes the latest version of this package unacceptable for internal use. With the increased dependency footprint comes a very significant maintenance cost and risk. Since Blaze depends on coverage, every change to `csslib`, `html`, or `plugin` becomes a Blaze-affecting change, which transitively affects the entire codebase. Due to that risk, Blaze-affecting changes are held to a much higher bar than others; testing, review and deployment follows a much more onerous process.

The current situation is that we're locked to an earlier version of coverage internally and I'm maintaining that working with dev-channel SDKs as they're rolled out. I'd really like to get us unforked. As an example of user impact, #107 was filed over a month ago, an internal fix was landed two days later, but it can't be pushed externally due the significant differences in the codebases. 

Moving to a vm service package is definitely the right thing to do, but replacing less than 500 loc of `devtools.dart` with tens of thousands of lines of analyzer, css and html manipulation, etc. is a no-go.

**Comment by kevmoo** [comment]
@cbracken most of those dependencies come via analyzer, which comes via `pkg/test`

Otherwise, I don't think the set of runtime dependencies is that much greater...

**Comment by zoechi** [comment]
Does coverage have to be a package dependency or can it also be used with `pub global run`?

**Comment by kevmoo** [comment]
It can be used via pub global run

**Comment by cbracken** [comment]
@zoechi the way coverage is run (from srcs or via a binary snapshot) is a separate issue to the dependency issue. * (gory details at bottom)

For background, internally absolutely everything is built hermetically from the ground up from source on every build/test/coverage run, all the way down to the Dart VM itself. Binaries (e.g. snapshots) are never checked in.

Blaze/[Bazel](http://bazel.io) is actually pretty clever and caches all build products across everyone's runs, so this works out to be pretty quick in practice. However, this means that on every commit, all build products in the transitive closure of reverse dependencies of the committed code are invalidated and need to be rebuilt. The worst case scenario for this is a change to something that blaze itself depends on; this transitively affects all code and build products and requires a lot of extra pain and special procedures as a result.

*  If you're curious we generally run all VM tools via snapshots -- but those snapshots are built from source immediately before running them. `pub run` is not used for internal work; we run collect_coverage, format_coverage and all other vm tools direct on the VM. If you're curious, an in-progress open-source version of these rules is [here](https://github.com/cbracken/bazel/blob/dart_rules/tools/build_rules/dart/vm.bzl#L23).

**Comment by cbracken** [comment]
@kevmoo thanks for clarifying.

Ripped out the test dep and we're down to 10. That's still a lot, but the set looks a lot more reasonable:
```
args 0.13.4+2
async 1.11.0
collection 1.8.0
json_rpc_2 1.2.0 (2.0.1 available)
logging 0.11.3
path 1.3.9
pub_semver 1.2.4
source_span 1.2.2
stack_trace 1.6.5
vm_service_client 0.1.3
```

**Comment by jtmcdole** [comment]
@cbracken, those actually look pretty decent.

**Comment by zoechi** [comment]
@cbracken thanks for the info

**Comment by cbracken** [comment]
Closing as ignoring test, things look pretty good.
