### ISSUE TITLE
Add tests to exercise collecting coverage from content-shell

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/coverage#122]
Currently the test suite for this project only exercises collecting coverage from a dart application running on the VM. This does not cover collecting coverage from content-shell.

I bring this up because Travis CI always uses the latest version of Dart, but at times there's an issue with the version of content-shell that it uses for CI builds (see https://github.com/travis-ci/travis-ci/issues/4406). If this package had tests to exercise content-shell coverage collection, those issues would potentially be caught by the CI build.

@cbracken @kevmoo

**Comment by cbracken** [comment]
Agreed -- getting coverage tests against content_shell checked into the repo is definitely valuable.

Think we also need a separate (non-coverage-specific) global canary test that checks the recency and health of content_shell tests on Travis as per that issue.

**Comment by cbracken** [comment]
Since Dartium and Dartium-based content-shell no longer exist, closing this as obsolete.
