### ISSUE TITLE
Get ahead of breaking change to service protcol

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/coverage#140]
https://groups.google.com/a/dartlang.org/d/msg/announce/VxSw-V5tx8k/wPV0GfX7BwAJ

Not sure what's needed – but would be great to validate

**Comment by cbracken** [comment]
Thanks for the heads up, fine sir!

**Comment by cbracken** [comment]
Update: expecting to land the fix for this this week. There are similar fixes needed in Flutter which I'll be making as well.

**Comment by cbracken** [comment]
Fixed in #155.
