### ISSUE TITLE
Request: add support for checked mode in `runAndCollect` function

### ISSUE THREAD

**Issue by cedx** [dart-lang/coverage#143]
I usually run my tests in checked mode in order to catch every possible error in continuous integration.

My tests are based on the [`test`](https://pub.dartlang.org/packages/test) package, and their runner has the checked mode enabled by default (see files [`vm/platform.dart`](https://github.com/dart-lang/test/blob/master/lib/src/runner/vm/platform.dart#L53), [`runner/browser/content_shell.dart`](https://github.com/dart-lang/test/blob/master/lib/src/runner/browser/content_shell.dart#L39) and [`runner/browser/dartium.dart`](https://github.com/dart-lang/test/blob/master/lib/src/runner/browser/dartium.dart#L60)).

I'm developing a [Grinder](https://github.com/google/grinder.dart) plugin that collects the code coverage using the `runAndCollect` function, and I would like that my tests to have the same behavior with or without coverage.

So it would be cool if an optional `bool checked` parameter were added.

**Comment by cbracken** [comment]
I wonder if we should default this to `true` in version 0.9.0. There are relatively few cases where developers should run tests in unchecked mode, so seems like a reasonable change to make.

Filed #146.

**Comment by cedx** [comment]
I share exactly the same opinion.
