### ISSUE TITLE
collect_coverage does nothing

### ISSUE THREAD

**Issue by eukreign** [dart-lang/coverage#166]
I'm running tests in content shell and trying to get a coverage report but can't seem to get coverage tool to do anything at all.

I start the test runner like so:
```
$ pub run test --pause-after-load test/editor/editor_test.dart
Warning: Debugging is currently unsupported on the Dart VM.

00:00 +0: [Dartium Content Shell] loading test/editor/model_test.dart

Observatory URL: http://127.0.0.1:42350/
Remote debugger URL: http://localhost:45598/devtools/inspector.html?ws=localhost:45598/devtools/page/3319C366-C0AB-490D-AB52-F494309775E8
The test runner is paused. Open the remote debugger or the Observatory and set breakpoints. Once
you're finished, return to this terminal and press Enter.
```

Once I get the debugger URL I start the coverage tool:
```
collect_coverage --uri="http://localhost:45598/devtools/inspector.html?ws=localhost:45598/devtools/page/3319C366-C0AB-490D-AB52-F494309775E8"
```

I then go back to the test runner and press Enter.

The tests all pass and the test runner exits but nothing is ever printed in the collect_coverage tool. There is no errors or any other messages. I also don't see any flags to make collect_coverage a little more verbose, maybe there would be clues about the problem.

Am I doing something wrong with how I use `coverage` or is this a bug?

Dart VM: 1.22.0-dev.10.1 (Sat Jan 28 19:46:18 2017) on "linux_x64"
Content Shell: linux-x64-dev-1.22.0-dev.10.1.0

**Comment by cbracken** [comment]
The URI you've specified doesn't look right to me -- you want to use the one from the line:
```
Observatory URL: http://127.0.0.1:42350/
```

Like this:
```
collect_coverage --uri=http://localhost:45598 
```

**Comment by eukreign** [comment]
This got me a little closer, I think...

There still appears to be an issue related to when the coverage starts and stops:

`collect_coverage` quits unexpectedly
=============================

I started the test runner as before:

```
$ pub run test --pause-after-load test/editor/editor_test.dart
Warning: Debugging is currently unsupported on the Dart VM.

00:00 +0: [Dartium Content Shell] loading test/editor/editor_test.dart
00:01 +0: [Dartium Content Shell] loading test/editor/editor_test.dart
00:02 +0: [Dartium Content Shell] loading test/editor/editor_test.dart

Observatory URL: http://127.0.0.1:36072/
Remote debugger URL: http://localhost:46635/devtools/inspector.html?ws=localhost:46635/devtools/page/CCC6F109-4358-42F8-BA6B-1099BA83AD66
The test runner is paused. Open the remote debugger or the Observatory and set breakpoints. Once
you're finished, return to this terminal and press Enter.
```

I start the collector with the observatory URL:

```
$ collect_coverage --uri=http://127.0.0.1:36072 -o coverage.json
```

After about a second, before hitting Enter in the test runner console, the test runner console displays the following:

```
Entering debugging console. Type "help" for help.
> 
```

If I wait another second or two, without doing anything, the `collect_coverage` command simply exits (with no coverage collected since the tests haven't even run yet).

If I hit Enter fast enough in the test runner before `collect_coverage` exits it does appear to collect some code coverage! Yay! But not consistently, other tests that I run appear to produce no coverage results.

**Comment by eukreign** [comment]
Maybe my issue is related to: https://github.com/dart-lang/coverage/issues/165
