### ISSUE TITLE
Is it possible to instrument "dart2js" generated files?

### ISSUE THREAD

**Issue by cedx** [dart-lang/coverage#195]
Starting with Dart 2.0, Dartium will be abandoned. How is it possible to generate code coverage for web projects that use only browser's JavaScript VM as test platform?

**Comment by cbracken** [comment]
@grouma for details, but I believe our solution for post-Dartium code coverage for web-based Dart code is Istanbul JS.

Once Dartium is fully deco'ed, I expect package:coverage will focus solely on VM/Flutter coverage.

**Comment by grouma** [comment]
Our current internal solution is to use Istanbul and remap-istanbul with DDC. The same tools won't work with Dart2JS given the tree shaking. We have discussed externalizing this support but it currently isn't a high priority. There is a tracking issue with package:test for coverage: https://github.com/dart-lang/test/issues/36

**Comment by cbracken** [comment]
Thanks - closing here in favour of dart-lang/test#36

**Comment by cedx** [comment]
Thanks for the clarification.
