### ISSUE TITLE
Support flag to mark a line hit only if all branches on that line are hit

### ISSUE THREAD

**Issue by cbracken** [dart-lang/coverage#197]
Today, if any token on a line is hit, the line is considered covered. It would be nice to support a flag that marks a line covered only if all tokens mapping to that line are hit.

As an example, today the following line is always considered covered if hit:
```dart
return foo == bar ? x : y;
```

**Comment by apaatsio** [comment]
Would this flag still be necessary *if* we had branch coverage as suggested in #141?

**Comment by cbracken** [comment]
@apaatsio you're entirely correct; branch coverage provides what this issue is requesting and more. Closing as a dupe of #141.
