### ISSUE TITLE
Coverage failing w/ 2.0.0-dev.5 sdk

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/coverage#200]
https://travis-ci.org/dart-lang/coverage/jobs/295851657

**Comment by cbracken** [comment]
I might be missing something, but this looks more like a pub timeout than something coverage-related.

**Comment by cbracken** [comment]
On re-running I get a failure. The good news is it's an intentional check I put in specifically to catch when the SDK containing the bugfix for #196 rolled out. Closing as dupe of #196.

**Comment by cbracken** [comment]
FYI tests updated in #201 for Dart SDK 2.0.0-dev.5.0 and #202 for Dart SDK 2.0.0-dev.6.0.
