### ISSUE TITLE
Dependency on args package should be bumped to allow args 1.0

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/coverage#210]
The pubspec.yaml for coverage specifies args at < 1.0 .  There is now a 1.0 version of args.

This is blocking rolling flutter to the 2.0 SDK, see https://github.com/flutter/flutter/pull/13223 .

cc @kevmoo @mit-mit

**Comment by cbracken** [comment]
Now released in v0.10.0.

**Comment by leafpetersen** [comment]
Sweet, thanks!

**Comment by leafpetersen** [comment]
@cbracken I think you need to bump the the version and publish, otherwise nobody sees this no?

**Comment by mit-mit** [comment]
@leafpetersen looks like the one in https://storage.googleapis.com/pub-packages/packages/coverage-0.10.0.tar.gz does have the args >= 1.0 dep.?

**Comment by kevmoo** [comment]
args >=1.0.0 <2.0.0

https://pub.dartlang.org/packages/coverage#-analysis-tab-

**Comment by cbracken** [comment]
@leafpetersen I remember publishing after I landed the Argos update, but definitely let me know if there’s anything I missed (e.g. constraint not quite right, etc.) and I’ll get a new version out.

**Comment by leafpetersen** [comment]
You're right, sorry - I was trying to diagnose why args still wasn't getting updated and saw that this commit didn't include the pubspec bump.  Forgot you did it as a separate step.

**Comment by cbracken** [comment]
Thanks for confirming!
