### ISSUE TITLE
Migrate to vm_service_lib

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/coverage#245]
`vm_service_client` is not actively maintained.

**Comment by kevmoo** [comment]
See also https://github.com/dart-lang/test/issues/976

**Comment by kevmoo** [comment]
@cbracken FYI

**Comment by kevmoo** [comment]
Would be great to run on this so we can discontinue `vm_service_client`. CC @mit-mit

**Comment by cbracken** [comment]
https://github.com/dart-lang/coverage/pull/256 completes this migration.
