### ISSUE TITLE
Coverage ignores if statement

### ISSUE THREAD

**Issue by apaatsio** [dart-lang/coverage#248]
Code coverage (as reported by `flutter test --coverage`) does not show any info for `if` statement.

## Code
```dart
void foo(bool returnImmediately) {
  if (returnImmediately) {
    return;
  }
  print('hello');
}
```
## Test code
```dart
foo(false);
```
## Expected output (generated with genhtml)
![coverage_bug_expected](https://user-images.githubusercontent.com/195210/54086750-a23d1b80-434c-11e9-8651-5ffc862f3440.png)

## Actual output (generated with genhtml)
![coverage_bug_actual](https://user-images.githubusercontent.com/195210/54086755-ad904700-434c-11e9-894f-b8e37519df0d.png)

You can see how the `if` and `return` statements are completely ignored which means that any reporting tool will report 100% line coverage for the code which is totally wrong.

## Tools used
```
❯ flutter --version
Flutter 1.2.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (3 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
❯ genhtml --version
genhtml: LCOV version 1.13
```

**Comment by ZichangG** [comment]
For branching and return statement, this is expected, since they are not a function calls. Currently, when VM prints coverage data, it only evaluates callsite data to determine whether a function has been called.

**Comment by leisim** [comment]
@ZichangG In my opinion this is not what a user of the coverage package expects. It can lead to undetected bugs :/

**Comment by apaatsio** [comment]
@ZichangG If this is the desired behavior, I'm having a hard time understanding why.

If we think of literal use cases, the current behavior is something along the lines "*As a software developer, I don't want code coverage tool to report all if statements*". That makes no sense to me.

It's also confusing that `return` statements inside `if`s are not reported but function calls are. I don't see why any developer or quality assurance engineer would want this behavior.

**Comment by ZichangG** [comment]
> It's also confusing that return statements inside ifs are not reported but function calls are.

We checked callsite data and return statements are obviously not counted.

I definitely agree that this behavior would be better if they can count branching and return statements in coverage report. But it will hurt the performance of VM with more counters. I am not sure whether it is worthy to do it by adding complexity to our codebase and also sacrificing the performance.

I'll reopen this issue and try to figure out anything I can do.

**Comment by vanlooverenkoen** [comment]
@ZichangG  I think the end goal of a coverage report is to detect if every line is tested. I thinks this must be fixed to make sure you have tested everything

**Comment by ZichangG** [comment]
> I think the end goal of a coverage report is to detect if every line is tested.

Agree on what you said. But as I mentioned previously, with the current structure, it has to add more checks in order to keep track of branches and return statements, which is likely to be a performance regression. Currently, we don't have a good solution for this.

**Comment by vanlooverenkoen** [comment]
I have no idea how it works internally but there is no way to add these extra checks only when running with --coverage?

**Comment by mraleph** [comment]
@ZichangG we actually should know if we ever entered `if` or not (at least in unoptimized code) - because we have edge counters at block entries. This would not work in optimized code though, unfortunately. 

@vanlooverenkoen Dart VM does not really have a special coverage mode. `--coverage` is a flag to flutter tools, not to the Dart VM. Right now VM just has a normal execution mode and flutter tool at the end ask VM to provide coverage report which is derived from the information that VM collects for other reasons (i.e. adaptive optimization). Certainly if VM had a special coverage collection mode we could be more aggressive with what kind of information we collect and thus provide more precise coverage for things. But it is not the case right now.

**Comment by vanlooverenkoen** [comment]
I think this should be a high prio for creating quality products. In dart or flutter.

**Comment by IchordeDionysos** [comment]
Relates to #344

**Comment by liamappelbe** [comment]
I've started working on branch coverage. Tracking bug is here: https://github.com/dart-lang/coverage/issues/141
