### ISSUE TITLE
Migrate to the latest package_config package

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/coverage#289]
~This is needed to unblock package:test users~ Note that this is no longer blocking as we are doing a non-breaking release of package_config. But we should still update once it is available.

**Comment by bkonyi** [comment]
I've gone ahead and ignored a deprecation warning [here](https://github.com/dart-lang/coverage/pull/294/files#diff-e69b5ffa817d530d3013ef3f912058d6R8). We'll want to remove that once this issue is resolved.
