### ISSUE TITLE
0.13.9 -> 0.13.10 contains a breaking change

### ISSUE THREAD

**Issue by felangel** [dart-lang/coverage#303]
Hello 👋  
I believe the function signature of `createHitmap` was changed in https://github.com/dart-lang/coverage/commit/51427863a4d1d8a857eeea4973bc3b8a2d94e44f#r39649905 which is a breaking change and is causing exceptions in other packages like `test_coverage`. Can we please revert this and publish the change in 0.14.0?

It's causing CI to fail unless we pin the version of coverage to 0.13.9 ([example](https://github.com/felangel/fresh/pull/21/checks?check_run_id=736410688))

**Comment by jakemac53** [comment]
cc @grouma

**Comment by jakemac53** [comment]
Note that we can't remove versions from pub, we can publish a revert release but that is equally breaking for anybody depending on the new behavior, if they have also already published. That still might be the best option though

**Comment by felangel** [comment]
I think it would be best to revert and publish 0.13.11. Then the breaking changes can be published as 0.14.0.

**Comment by jakemac53** [comment]
@pasindud do you have packages published on pub which already rely on this new signature?

**Comment by pasindud** [comment]
no, I don't,
I just commented on https://github.com/flutter/flutter/pull/58658 before @jonahwilliams updates flutter coverage

**Comment by jakemac53** [comment]
Ok, then probably others haven't noticed the change yet and updated, a revert and re-publish as 0.14.0 sounds good to me.

**Comment by grouma** [comment]
I'll get that done today. Sorry about the break!

**Comment by grouma** [comment]
Published a revert.
