### ISSUE TITLE
update README.md to explain how to use `pub global` to run the script

### ISSUE THREAD

**Issue by zoechi** [dart-lang/coverage#31]
Isn't this a perfect candidate to use the new `pub global` feature to run the script?

```
pub global activate coverage
pub global run coverage:collect_coverage --port=NNNN -o coverage.json --resume-isolates
```
I assume `pub global` has not yet landed in stable, but can't be long ;-)

**Comment by cbracken** [comment]
Agreed - this makes perfect sense. I think it makes sense to land #36 done first, then follow up with this request.

**Comment by cbracken** [comment]
Readme is updated via your patch c5d8f7caccdfa6c3b8aa8c520749c144572ba7e5. Thanks!
