### ISSUE TITLE
format_coverage seems to be broken

### ISSUE THREAD

**Issue by isoos** [dart-lang/coverage#316]
In pub site's code coverage checks we were running format_coverage outside of the main package's directory. Prior to a change a couple of weeks ago (on `coverage 0.13.0`), this was working fine, however, the latest stable version (`0.14.1`) seems to be broken. If I run it outside of the main package directory, it only reports files from the `test/` directory, and none of the `lib/` files are reported. However, if I run the `format_coverage` from inside the main package, all of the files are reported correctly.

Related fix on pub-dev: https://github.com/dart-lang/pub-dev/pull/4169

**Comment by liamappelbe** [comment]
The .packages file is deprecated. If you're running outside of the package root, pass the package root dir to `--package`.
