### ISSUE TITLE
Plans to release 0.14.2

### ISSUE THREAD

**Issue by illia-romanenko** [dart-lang/coverage#319]
Hi 👋 ,

thanks for your work on coverage support and this library. We stumbled upon an issue resolved in 0.14.2 but it's not released yet - any plans to release it soon? 

Currently, as a workaround, we can use dependency_override but it would be great if it's released and official so other users can benefit from the fix (and save some time :) )

Have a good day!
Illia

**Comment by cbracken** [comment]
Oh yikes! Thanks for checking!

I'll take a look to see what's up today, and if it's good to publish, I'll do so. Either way, I'll post an update today.

**Comment by cbracken** [comment]
Question for @grouma @bkonyi @jakemac53 -- it looks like the last tagged version for the repo is 0.13.8, but I see that we've published 0.13.8, 0.13.9, 0.13.10, 0.13.11, 0.14.0, and 0.14.1. Could someone go back and tag those? It's unclear to me what was last released from the repo history.

I've created https://github.com/dart-lang/coverage/pull/320 to tag 0.14.2 for release.

**Comment by cbracken** [comment]
Version 0.14.2 was cut at #320, tagged at https://github.com/dart-lang/coverage/tree/0.14.2.

It's now [published to pub](https://pub.dev/packages/coverage/versions).

**Comment by illia-romanenko** [comment]
Thanks! That was quick!
