### ISSUE TITLE
Use service library from Observatory

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/coverage#32]
Service library in Observatory can handle all communication over the service (to content_shell, standalone, and Chrome VM) and provides model objects for responses. It should allow you to drop a bunch of code.

**Comment by cbracken** [comment]
f3dfba44dd038742857c1b9c01adbaf2080f6838 killed off `devtools.dart` and moved us over to `package:vm_service_client`, which technically resolves this issue. Unfortunately it also increased the set of transitive deps from args, logging, and path to 36 packages. 

Until we've got that issue (#109) sorted, I'd prefer to keep this issue open.

**Comment by cbracken** [comment]
Now using the [vm_service_client](https://pub.dartlang.org/packages/vm_service_client) package.
