### ISSUE TITLE
Upgrade dependencies to null_safety

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/coverage#321]
Hey!

I have the following problem blocking my migration to null_safety:

```
Because test >=1.16.0-nullsafety.7 depends on coverage >=0.13.4 <0.15.0 which depends on logging >=0.9.0 <0.12.0, test >=1.16.0-nullsafety.7 requires logging >=0.9.0
  <0.12.0.
```

My package depends on `logging: ^1.0.0-nullsafety.0` and `test: ^1.16.0-nullsafety.9`.

It seems to me the problem is that this package has not migrated all its dependencies yet, specifically, the `logging` dependency.

Could you please have a look and publish a package that works with null_safety?

Thanks!

**Comment by mannprerak2** [comment]
@cbracken is there any timeline for this?

**Comment by dnfield** [comment]
In particular, this needs null safe vm_service so that other packages upstream can use it.

**Comment by sarahec** [comment]
The easy patch to the Logging incompatibility is to change the upper version bound from `<0.12.0` to include 1.0.0

1.0.0-nullsafety.0 has a backwards-compatible API on dart 2.10.0 or later.
