### ISSUE TITLE
Migrate to package_config

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/coverage#367]
The `.packages` file is [being discontinued](https://github.com/dart-lang/sdk/issues/48272), so we should migrate to `package_config.json` (or rather its [public API](https://pub.dev/documentation/package_config/latest/)). 

Some current uses:
https://cs.github.com/dart-lang/coverage?q=.packages

**Comment by liamappelbe** [comment]
Looks like we already support package_config.json, and just use .packages as a fallback (see _parsePackages in resolver.dart). There's a few tests and tools to migrate though.

**Comment by liamappelbe** [comment]
Users can pass .dart_tool/package_config.json or .packages to the --package flag in format_coverage. But it would probably make more sense to deprecate this flag and add a --package flag that takes the root directory of the package and uses findPackageConfig.
