### ISSUE TITLE
`test_coverage` appears abandoned, and `test_cov` doesn't have issue tracker, `flutter test --coverage` requires Flutter SDK

### ISSUE THREAD

**Issue by bradyt** [dart-lang/coverage#372]
I'm hoping Dart team considers that test coverage should be convenient to use.

The `test_coverage` project has gone relatively silent. There is a fork, `test_cov`, which works, but as I run into issues, there is no issue tracker to at least ensure everyone is aware of any issues.

There is `flutter test --coverage`, but I do not want to have a Flutter SDK dependency for all tests on CI. I use custom Docker images, reviewing CI locally, and pushing new Docker images to remote, and prefer to use Docker images that don't contain the Flutter SDK for many aspects of a project.

On the other hand, while the feature to exit with an error is gone from the `test_cov` fork, that feature has been restored by the slightly orthogonal project, `dlcov`.

So I'm hoping someone in Dart team or community can make sure that test coverage is a provided feature.

**Comment by liamappelbe** [comment]
Yeah, it seems the current pattern is for users to write a little shell script like this:

```bash
dart pub global activate coverage
dart run --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=1234 test &
dart pub global run coverage:collect_coverage --wait-paused --uri=http://127.0.0.1:1234/ -o coverage.json --resume-isolates --scope-output=foo
dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --lcov -i coverage.json -o lcov.info
```

It would be nice if we had a tool that did this automatically, since gathering test coverage is the main use case.

It's easy enough to add a dart script to our bin/ directory that does the same thing as that shell script. Are there any other features a tool like that needs?
