### ISSUE TITLE
Function coverage stuck printing "tokenPos <#> in function <function_name> has no line mapping for script <package>"

### ISSUE THREAD

**Issue by getBoolean** [dart-lang/coverage#389]
I am running this command `dart pub global run coverage:test_with_coverage --function-coverage`

It gets stuck printing thousands of these lines.

```
...
tokenPos 5880 in function copyWith has no line mapping for script package:shu_epub/src/features/package/data/tours/epub_single_tour.dart
tokenPos 6088 in function toMap has no line mapping for script package:shu_epub/src/features/package/data/tours/epub_single_tour.dart
tokenPos 6234 in function EpubSpine.fromMap has no line mapping for script package:shu_epub/src/features/package/data/tours/epub_single_tour.dart
tokenPos 6515 in function toJson has no line mapping for script package:shu_epub/src/features/package/data/tours/epub_single_tour.dart
tokenPos 6561 in function EpubSpine.fromJson has no line mapping for script package:shu_epub/src/features/package/data/tours/epub_single_tour.dart
...
```

Logs: https://github.com/getBoolean/shu_epub/runs/6533902903?check_suite_focus=true

Am I missing a step?

**Comment by liamappelbe** [comment]
Does it work without the function coverage flag?

**Comment by getBoolean** [comment]
> Does it work without the function coverage flag?

I haven't tested it recently, but when I had tested it, it only happened with the function coverage flag

**Comment by liamappelbe** [comment]
Function coverage is not sufficiently tested. I need to fix that. I tried running function coverage on one of my own repos, and I found a few bugs.

Like you, I got a bunch of errors saying that a function was missing a line mapping. However all my cases were where the tokenPos was -1, which just means that the tokenPos is missing for that function (probably a VM bug). That's a very different error to what you're seeing, where we have a valid tokenPos, but it's not found in the script's token positions.

Do you notice anything about the functions it's complaining about? For example, are those functions uncompiled (never called), or abstract methods, or are they extension methods?

**Comment by liamappelbe** [comment]
I've nailed down a few cases where we're missing token positions:

- Extension methods, but I'm still seeing these functions as covered, so there must be 2 methods generated (one of which is probably abstract or something).
- The empty constructors that are automatically generated for classes that don't have them (for some reason these are not marked as implicit in the service API).
- The implicit getter and setter functions for class fields are also causing issues, but I have a separate PR to ignore those.

So I think it's ok to just silence this error.

I'm a bit confused about the missing tokens in your errors. Eg `EpubSpine.fromMap` is defined in [this file](https://github.com/getBoolean/shu_epub/blob/c471e6aa0f665ed1c59bd405c251d982430976e9/lib/src/features/package/data/spine/epub_spine.dart#L135), but the error is looking in [this file](https://github.com/getBoolean/shu_epub/blob/main/lib/src/features/package/data/tours/epub_single_tour.dart). Maybe it has something to do with these being part files?
