### ISSUE TITLE
Which license is used in this project?

### ISSUE THREAD

**Issue by romayankin** [dart-lang/coverage#420]
Dear authors,

I can see that each source file in this project is referencing BSD-Style license, however the LICENSE file as well as the front page of the project is referencing Apache-2.0 license - which is confusing as what's the point in Apache license if every source file is under BSD?

Can you please clarify which license is the main license of this project?

Thanks,
Roman

**Comment by devoncarew** [comment]
Thanks for the inquiry! It does look like every file in the repo has a BSD header, but the repo license file is Apache. Given that all the files in the repo are licensed under BSD, I think we'll switch the repo license file to our std Dart BSD license.
