### ISSUE TITLE
Running coverage in new flutter project

### ISSUE THREAD

**Issue by Malnen** [dart-lang/coverage#431]
Hi
I'm trying to run a test coverage in a new flutter project. After creating the project, there is one dart file with a sample widget and one test file. When I try to run `dart pub global run coverage:test_with_coverage` or `flutter pub global run coverage:test_with_coverage` I get an error that it cannot find test package. When I try  `flutter pub run coverage:test_with_coverage`, I need to pass a test path but then i'm getting following error **Error: Not found: 'dart:ui' import 'dart:ui'** 

Is it possible to run test coverage for flutter widgets with this package?

**Comment by christopherfujino** [comment]
With flutter apps, you have to use `flutter test` in order to provide dart:ui. Since the flutter CLI tool depends on this package, it's available via:

```
$ flutter test --coverage
```
