### ISSUE TITLE
Unable to get collect_coverage to work with Dartium; always quits too soon

### ISSUE THREAD

**Issue by DanTup** [dart-lang/coverage#49]
A some point, this script worked, but intermittently. Since upgrading to Windows 8.1, it just doesn't work at all. I've tried everything, including --wait-paused, kickin off Dartium both before and after collect_coverage, but collect_coverage always quits as soon as Dartium loads, and doesn't wait for the tests to finish executing.

What is the correct way to make this work?

Note: I'm usig 0.5.0, because 0.6.0 just crashes immediately (I'll raise another case for that shortly).

```powershell
$testInstance = "http://dart-tests/"
$dartiumPath = "C:\Work\Utilities\dartium\chrome.exe"
$dartiumProfilePath = "C:\Work\Utilities\dartium-profile"
$timeoutSeconds = 10
$debuggerPort = 8091
$dartSDK = "%DART_SDK%"

# Start listening for coverage
Write-Host "Starting collect_coverage..."
$proc = Start-Process pub -ArgumentList ("global", "run", "coverage:collect_coverage", "--port=$debuggerPort", "-o coverage/coverage.json", "--connect-timeout=$timeoutSeconds") -PassThru

# Start Dartium and run the tests
Write-Host "Starting Dartium to run tests..."
$dartium = Start-Process $dartiumPath -ArgumentList ("--remote-debugging-port=$debuggerPort", "--user-data-dir=$dartiumProfilePath", "--disable-web-security", $testInstance) -PassThru

# Wait long enough for the tests to finish
Write-Host "Waiting for tests to finish..."
sleep ($timeoutSeconds + 1)

# Kill dartium
Write-Host "Killing Dartiumn processes..."
$dartium | kill

# Wait for coverage to end
Write-Host "Waiting for collect_coverage to finish..."
$proc.WaitForExit()

# Format coverage
Write-Host "Formatting coverage..."
dart tool\format_coverage.dart
```

**Comment by cbracken** [comment]
Which version of the SDK are you using? As of SDK 1.9.0-dev.7.1 the old observatory protocol was replaced by a new websocket-based protocol and support was removed for connecting over Chromium Remote Debugging protocol. 

Instead, newer versions Dartium emit a line to stdout that looks something like `Observatory listening on http:127.0.0.1:someport`, to which you need to connect (using v0.6.0).

**Comment by DanTup** [comment]
I downloaded both the SDK and Dartium from this page today:

https://www.dartlang.org/tools/download.html

I can't check the versions now (I'm at home), but they should be latest stable?

**Comment by DanTup** [comment]
Oops, I posted the versions in another issue.. Here they are:

Dart VM version: 1.8.5 (Tue Jan 13 13:38:34 2015) on "windows_x64".
Dartium version is 38.0.2125.0 (Developer Build 292384).

**Comment by DanTup** [comment]
Ok, re-read what you said. I'm using 0.5.0 because 0.6.0 crashes (see Issue #50), so I guess this is expected and user error!
