### ISSUE TITLE
Collecting coverage from dartium or content_shell fails due to JsonRpcError

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/coverage#98]
This seems to be a problem ever since Dart SDK 1.11.

**Usage:**
```
$ dartium --remote-debugging-port=8024 test/example_test.html
[87984:1291:0806/145141:ERROR:renderer_main.cc(207)] Running without renderer sandbox
[87985:1291:0806/145141:ERROR:renderer_main.cc(207)] Running without renderer sandbox
Observatory listening on http://127.0.0.1:54563
Observatory listening on http://127.0.0.1:54564
```
```
$ pub run coverage:collect_coverage --port=54563 -o coverage.json --resume-isolates
JsonRpcError: VM must be paused (101)
```

> Side Note: Is `--remote-debugging-port` necessary? As I understand it, observatory picks its own ports for each tab and there's no way to force it to use a certain port (at least not yet).

**Full Error Stacktrace:**
```
JsonRpcError: VM must be paused (101)
dart:async                                       _Completer.completeError
package:coverage/src/devtools.dart 227           _Connection._handleResponse
===== asynchronous gap ===========================
dart:io                                          _WebSocketImpl.listen
package:coverage/src/devtools.dart 184           _Connection._Connection
package:coverage/src/devtools.dart 191           _Connection.connect.<async>
===== asynchronous gap ===========================
dart:async                                       _Future.then
package:coverage/src/devtools.dart 190           _Connection.connect.<async>
===== asynchronous gap ===========================
dart:async                                       Future.Future.microtask
package:coverage/src/devtools.dart               _Connection.connect
package:coverage/src/devtools.dart 93            VMService.connectToVMWebsocket.<async>
===== asynchronous gap ===========================
dart:async                                       Future.Future.microtask
package:coverage/src/devtools.dart               VMService.connectToVMWebsocket
package:coverage/src/devtools.dart 89            VMService.connect.<async>
===== asynchronous gap ===========================
dart:async                                       Future.Future.microtask
package:coverage/src/devtools.dart               VMService.connect
package:coverage/src/collect.dart 17             collect.<async>.<fn>
package:coverage/src/util.dart 38                retry.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:coverage                                 retry.<async>.<fn>
package:coverage/src/util.dart 17                retry.<async>._withTimeout
package:coverage/src/util.dart 35                retry.<async>
===== asynchronous gap ===========================
dart:async                                       Future.Future.microtask
package:coverage/src/util.dart                   retry
package:coverage/src/collect.dart 16             collect.<async>
===== asynchronous gap ===========================
dart:async                                       Future.Future.microtask
package:coverage/src/collect.dart                collect
http://localhost:51502/collect_coverage.dart 21  main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                              Chain.capture
http://localhost:51502/collect_coverage.dart 20  main.<async>
```

**Comment by evanweible-wf** [comment]
@cbracken @kevmoo

**Comment by cbracken** [comment]
> Side Note: Is --remote-debugging-port necessary?

It was necessary until quite recently. Around v1.9 or 1.10 of Dartium, it was moved to its own port and we eliminated the old chrome-remote-debugging websocket protocol. Given that we've started eliminating support for older observatory protocols in this package, we can remove that from the instructions.

**Comment by evanweible-wf** [comment]
@cbracken I was using 1.11.1, but I just upgraded to 1.11.3 and saw the same issue. I can try the development channel and see if that helps.

**Comment by evanweible-wf** [comment]
@cbracken okay I tried it with the latest dev version (1.12.0-dev.5.1) and still got the same error.

**Comment by evanweible-wf** [comment]
@cbracken @kevmoo any ideas on this? Are either of you able to reproduce what I'm seeing?

**Comment by kevmoo** [comment]
@evanweible-wf Did this work in 1.10? I'll take a look quick...

**Comment by evanweible-wf** [comment]
@kevmoo I dug into this a bit more. I stepped back through the commit history and found https://github.com/dart-lang/coverage/commit/f5b4ef8952d07b074c382577f8a5e0ec37ec04be to be the commit that introduces the code that throws the RPC error. Ever since that commit, browser coverage fails due to that error, but I think it's a false negative prior to 1.11.

If I use the commit just before that one (https://github.com/dart-lang/coverage/commit/0d8d90327fd929c78eb56d04ae3fbb96a1f574bd), I get the following results:
- 1.10.0: coverage collects successfully
- 1.10.1: coverage collects successfully
- 1.11.0: 
    ```
    SEVERE: 2015-08-13 16:36:29.492: Failed to get JSON response for message 2
    The null object does not have a method '[]'.
    ```

So it looks like 1.11 is when the protocol communication changes and browser coverage actually stops working.

Also, I erroneously wrote above in the original issue description that I was trying to run dartium with a `.dart` file - obviously that doesn't work. It was supposed to be an `.html` file that simply loads a `.dart` script. I've updated that now.

**Comment by kevmoo** [comment]
Interesting...will let you know what I come up w/

**Comment by kevmoo** [comment]
Closing. User error. Please open an issue about a better error message – it wasn't very clear that resume is only needed if things are paused. :smile:

**Comment by evanweible-wf** [comment]
Thanks again! :)
